name: Workflow B

on:
  push:
  workflow_dispatch:

jobs:
  main-b:
    runs-on: self-hosted
    steps:
      - name: Sleep and exit
        run: |
          sleep 20
          exit 0
  call-c:
    needs: main-b
    uses: ./.github/workflows/c.yml
