name: Workflow C

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: workflow-c
  cancel-in-progress: false

jobs:
  main:
    runs-on: unbuntu-latest
    steps:
      - name: Sleep and complete
        run: |
          sleep 180
          exit 0
