name: Workflow C

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: workflow-c
  cancel-in-progress: false

jobs:
  main-c:
    runs-on: self-hosted
    steps:
      - name: Sleep and complete
        run: |
          sleep 30
          exit 0
